#!/bin/sh


sudo apt-get update
sudo apt-get install git-core curl build-essential openssl libssl-dev
git clone https://github.com/joyent/node.git
cd node
git checkout v0.12.7
sudo ./configure

sudo make
sudo make install
